### ISSUE TITLE
Wrong number of titles in user library

### ISSUE THREAD

**Issue by theitchtime** [Smart123s/ItchClaim#15]
When reloading the cache of the user's library, the report claims I have 50 more titles than actual.

https://github.com/Smart123s/ItchClaim/blob/master/ItchClaim/ItchUser.py#L183-L192

Itch is reading page0, page1, page2, page3 -- page0 and page1 give identical results from url testing. Range should start from 1 to give accurate count.

**Comment by theitchtime** [comment]
I think range is backwards - 
`1, int(1e18)`

**Comment by Smart123s** [comment]
Thanks, I don't know how I mixed them up.
