### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by nnoc** [Smart123s/ItchClaim#3]
Hey! I was wondering if it's just me that gets an error now with the script due to Error code: SEC_ERROR_EXPIRED_CERTIFICATE.
Is there something we can do to help?

Thanks for your work!

**Comment by Smart123s** [comment]
Hi, thanks for the heads-up. It should be fixed now. The issue was with my DNS configuration. GitHub Pages [doesn't](https://github.com/orgs/community/discussions/22398#discussioncomment-3236557) support chimed CNAME records.
