### ISSUE TITLE
Make links detectable on site

### ISSUE THREAD

**Issue by DealsBeam** [Smart123s/ItchClaim#4]
Hello there,

are you able to make the links on the site detectable so they can be picked up by this userscript https://github.com/HCLonely/user.js#redeem-itchio / https://greasyfork.org/zh-CN/scripts/36806-redeem-itch-io what it basically does is you can run it to detect every game on page and claim them automatically

Thank you

**Comment by Smart123s** [comment]
The second script you provided (https://greasyfork.org/en/scripts/36806-redeem-itch-io/code), only looks for links on certain sites, defined in line 83 (line 84 for the first script). You could try adding my site to that list, and check if it works?

**Comment by DealsBeam** [comment]
I tried to add your site and freetchio as well and it doesn't work for me, could possibly be that I didn't do it right (I don't know code)

**Comment by Smart123s** [comment]
I don't really have the time to look at it now, but I'll check it out once
I get some free time. No ETA.

**Comment by DealsBeam** [comment]
The script developer has added ItchClaim https://github.com/HCLonely/user.js/issues/11#issuecomment-1694912189

**Comment by Smart123s** [comment]
Cool, thanks for letting me know. I'm closing the issue now. If it doesn't work for some reason, feel free to reopen it.
