### ISSUE TITLE
Website not updating

### ISSUE THREAD

**Issue by Alhaitham** [Smart123s/ItchClaim#8]
Hello

Just a heads up the the websites is not updating with new sales

It seems that it is checking them but not adding them

Last sale added was number 111466

Thanks

**Comment by Smart123s** [comment]
Should be fixed by https://github.com/Smart123s/ItchClaim/commit/9e73d6d895a9acaca5f9727a8d6119a9b4ee093b
Rechecked all sales from [111523](https://itch.io/s/111523/new-year-new-forms-a-strip-of-velvet-reborn)
